### ISSUE TITLE
does not compile

### ISSUE THREAD

**Issue by Bennedetto** [cetrespeo/ESP32-E-Paper-Weather#2] opened 2019-01-26 21:41 UTC
Does not compile at all using Arduino 1.8.5.
I configured to use display type WS4c;
in folder "GxGDEW042Z15" the file "GxGDEW042Z15.h" tries to include "#include "../GxEPD.h", which is not existing.

**Comment by cetrespeo** [comment] 2019-01-28 11:26
First commented lines of .ino code recommend using the dependency libraries. 

Added to root dir, but remember to update those files with the dependencies as they are frequently updated.

Also note I updated the .ino and auxiliar files to add TTGO T5 2,9" support. Now working on 5,8" GD

**Comment by digits1** [comment] 2019-11-28 17:48
Hello cetrespeo! Loved your project, but there 's a problem. I can 't compile a sketch. Can I ask you what the problem is? Thanks.
![ESP32](https://user-images.githubusercontent.com/26040876/69825442-6e7a8c80-1220-11ea-9134-87f22019bcfb.png)

**Comment by cetrespeo** [comment] 2019-11-28 21:22
Thanks.

You need to add TimeLib library. 

I got rid of that library a few months ago in rev 1.5 as there are a lot of Time libraries and installation is a bit messy. I thought no one was using this code so I didn't maintain the GitHub. Sorry. 

I will try to update the source soon. Many bugs are fixed now, and requirements simplified, but as long as this project is one of my beta-testing projects, I continue adding stupid things and messing it up again ;-)

Anyway, please try TimeLib (it is quite messy as there are a lot of time libraries) and in case you don't find the right TimeLib, please wait a few days until I update the new rev 1.53 

I am now getting rid of this Firebase approach, but I didn't finished a proper stable revision.

Thanks for your appreciation.

**Comment by cetrespeo** [comment] 2019-11-29 09:36
Source updated. Please try new rev 1.54.

**Comment by digits1** [comment] 2019-11-29 17:52
Good evening! Thank you for the answer. I almost did it, but there was another mistake. I can 't understand the reason
![32](https://user-images.githubusercontent.com/26040876/69884538-f8daf300-12e9-11ea-8290-360aca97908f.png)

**Comment by cetrespeo** [comment] 2019-11-29 19:41
Good evening! 

This morning I tried from scratch and got it running on first. Which ESP32 library rev are you running?

Could you please send me an snapshot of the end of your Arduino Library Manager Installed list?. It is something like
![image](https://user-images.githubusercontent.com/14995096/69887604-1e66fd00-12e8-11ea-940c-db398437efd9.png)

You should have everything but FastLed and Firebase ESP32 Client (I have those for the future revs). Nothing more is required to run the 1.54

**Comment by digits1** [comment] 2019-11-30 14:42
Hello! Nothing happened the same mistake. Sharing screenshots and installed libraries with you in my version. There was an idea, could you compile my version of the sketch? Thus check for errors, or share the .bin file (after compilation) My e-mail: digits1@yandex.ru Thank you so much!
![1](https://user-images.githubusercontent.com/26040876/69901918-c4724000-1398-11ea-8407-7491c0904101.png)
![2](https://user-images.githubusercontent.com/26040876/69901919-c4724000-1398-11ea-8db3-573897adcb31.png)

**Comment by cetrespeo** [comment] 2019-12-03 09:04
Solved.

**Closed as completed by cetrespeo** 2019-12-03 09:04 UTC
